apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jenkins-config
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  jenkins.yaml: |-
    jenkins:
      systemMessage: "Jenkins configured automatically by JCasC"
      numExecutors: 1
      securityRealm:
        local:
          allowsSignup: false
          users:
              name: "{{ .Values.admin.name }}"
              password: "{{ .Values.admin.password }}"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
    
    jobs:
      - script: >
          job('{{ .Values.job.name }}') {
            description('{{ .Values.job.description }}')
            steps {
              shell('{{ .Values.job.command }}')
            }
          }