apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.admin.name | b64enc | quote }}
  jenkins-admin-password: {{ .Values.admin.password | b64enc | quote }}