apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  - port: 50000
    targetPort: jnlp
    protocol: TCP
    name: jnlp
  selector:
    app: jenkins
    release: {{ .Release.Name }}