apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-plugins
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  plugins.txt: |-
    {{- range .Values.plugins }}
    {{ . }}
    {{- end }}