image:
  repository: 753350392043.dkr.ecr.eu-west-1.amazonaws.com/rs-flask-app
  tag: v3
  pullPolicy: Always

imagePullSecrets:
  - name: aws-ecr-secret

env:
  - name: FLASK_APP
    value: "main.py"
  - name: FLASK_RUN_HOST
    value: "0.0.0.0"
  - name: FLASK_RUN_PORT
    value: "8080"

service:
  type: NodePort
  port: 8080
  nodePort: 30082